### PR TITLE
Add Userlist

### PR DESCRIPTION
**Pull request by benedikt**
Hey @CalvinWalzel,

thanks for starting this project. We'd love to be part of it by being listed. 

I've added Ember.js to the stacks in the process. Happy to tweak the colors if needed. 

- Benedikt

### CODE REVIEW

**Comment by CalvinWalzel** [comment]
There's currently a merge conflict because a pull request I've merged earlier also added Ember.

Theirs looks like this:
Screenshot 2023-03-21 at 23 28 51@2x

Yours looks like this:
Screenshot 2023-03-21 at 23 28 34@2x

After looking at the ember brand guide, I'd say that yours is actually a more faithful representation of the brand colors & more aligned with the styling of this page.

Could you resolve the merge conflict with your changes? Many thanks :)

**Review by CalvinWalzel — APPROVED** [review]
Hey @benedikt, thank you for the contribution! The entry looks good. I think the image is a bit on the large size, but if necessary we can always still resize it later :)

**Comment by benedikt** [comment]
@CalvinWalzel Rebased the branch and resized the logo to 400x400 👍

**Review by CalvinWalzel — APPROVED** [review]
Looks good to me :)

**Pull request merged**
